Repository unb-academic/dashboard, pull requests merged in 2022-09, with the labels that each got.

#3 Adaptação para funcionamento local
  data_migrator.py
  functions.py
  graphs/average.py
  graphs/fertility.py
  graphs/migration.py
  graphs/population.py
  graphs/urban_population.py
  main.py
Labels: melhoria, procura-se ajuda

#4 Organizar a semântica do código
  graphs/average.py
  graphs/fertility.py
  graphs/migration.py
  graphs/population.py
  graphs/urban_population.py
  main.py
  requirements.txt
Labels: melhoria

#6 Melhorar a globalização da variável de dataframe
  data_migrator.py
Labels: melhoria

#7 Melhorar semântica de código
  functions.py
  graphs/average.py
  graphs/fertility.py
  graphs/migration.py
  graphs/population.py
  graphs/urban_population.py
  main.py
  utils.py
Labels: melhoria

#15 Utilizar recursos nativos do Python 3.10
  data_migrator.py
Labels: melhoria

#10 Abstrair gráficos e criar funções de filtros
  graphs/average.py
  graphs/fertility.py
  graphs/migration.py
  graphs/population.py
  graphs/urban_population.py
  main.py
Labels: melhoria, prioridade

#19 Consertar tipagem de código
  graphs/average.py
  graphs/fertility.py
  graphs/migration.py
  graphs/population.py
  graphs/urban_population.py
  main.py
  utils.py
Labels: bug, melhoria

#20 Implementar filtro de população urbana
  graphs/urban_population.py
  main.py
Labels: melhoria

#21 Implementar filtro de taxa de fertilidade
  graphs/fertility.py
  graphs/urban_population.py
  main.py
  utils.py
Labels: melhoria, prioridade

#23 Implementar filtro de percentual populacional
  graphs/population.py
  main.py
  requirements.txt
  utils.py
Labels: melhoria, prioridade

#24 Padronizar código de acordo com as convenções da PEP-8
  graphs/migration.py
  graphs/population.py
  graphs/urban_population.py
  main.py
  utils.py
Labels: melhoria

#26 Adicionar informações adicionais no README
  README.md
Labels: documentação

#29 Organizar importações do projeto
  graphs/population.py
  main.py
Labels: melhoria

#28 Implementar filtro de média de idades
  graphs/average.py
  main.py
  utils.py
Labels: melhoria, prioridade
